# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_username', models.CharField(default='', max_length=10, null=True, verbose_name='ssh用户名')),
                ('ssh_userpasswd', models.CharField(default='', max_length=40, null=True, verbose_name='ssh用户密码')),
                ('ssh_hostip', models.CharField(default='', max_length=40, null=True, verbose_name='ssh登录的ip')),
                ('ssh_host_port', models.CharField(default='', max_length=10, null=True, verbose_name='ssh登录的端口')),
                ('ssh_rsa', models.CharField(default='', max_length=64, verbose_name='ssh私钥')),
                ('rsa_pass', models.CharField(default='', max_length=64, verbose_name='私钥的密钥')),
                ('ssh_status', models.IntegerField(default=0, verbose_name='用户连接状态,0-登录失败,1-登录成功')),
                ('ssh_type', models.IntegerField(default=0, verbose_name='用户连接类型, 1-rsa登录,2-dsa登录,3-ssh_rsa登录,4-docker成功,5-docker无法登录')),
                ('sn_key', models.CharField(default='', max_length=256, verbose_name='唯一设备ID')),
            ],
            options={
                'verbose_name': '用户登录信息表',
                'verbose_name_plural': '用户登录信息表',
                'db_table': 'connectioninfo',
            },
        ),
    ]
